sotopia_env: '/Users/xuankeyang/Desktop/social-decipher/data/scenario.jsonl'
sotopia_hard_env: '/Users/xuankeyang/Desktop/social-decipher/data/scenario_hard.jsonl'

env: '/Users/xuankeyang/Desktop/social-decipher/data/processed_scenarios_200.jsonl'
hard_env: '/Users/xuankeyang/Desktop/social-decipher/data/processed_scenarios_hard.jsonl'

# Key
OPENAI_API_KEY: "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"
HF_API_TOKEN: "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"
MISTRAL_API_KEY: yQ9wm2nsnrlujAjTbBDuRwnjTV2bA1oT