data_dir: 'data/episode_all_neutralized.jsonl'

models:
  model_a: "gpt-4o-mini"
  model_b: "Qwen/Qwen2.5-7B-Instruct"
  gpu: "0,1,2,3"
  vllm_port: 7900
  chat_template: "configs/qwen2.5-7b.jinja"
  served_model_name: "qwen2.5-7b-instruct"
  max_model_len: 4096
  tensor_parallel_size: 0
  enable_repair_and_state: false

## Key
AGENT_OPENAI_API_KEY: ""
EVALUATOR_OPENAI_API_KEY: ""

HF_API_TOKEN: ""
MISTRAL_API_KEY: ""

